MusicStore/MusicStore/Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MusicStore.Models
{
    public class Album
    {
        public int AlbumID { get; set; }
        [Display(Name ="Genre")]
        public int GenreID { get; set; }
        [Display(Name = "Artist")]
        public int ArtistID { get; set; }
        public string Title { get; set; }
        public int Price { get; set; }
        [Display(Name = "Album Art")]
        public string AlbumArtUrl { get; set; }

        public Genre Genre { get; set; }
        public Artist Artist { get; set; }
    }
}

MusicStore/MusicStore/Areas/Admin/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicStore.Data;
using MusicStore.Models;
using MusicStore.Models.ViewModels;

namespace MusicStore.Areas.Admin
{
    [Area("Admin")]
    [Authorize (Roles = "Administrator")]
    public class AlbumsController : Controller
    {
        private readonly StoreContext _context;     


        public AlbumsController(StoreContext context)
        {
            _context = context;
        }

        public IActionResult ListGenres(int? genreID,int? artistID,string id)
        {
           
            
            var albums = from a in _context.Albums
                         .Include(a => a.Genre)
                         .Include(a => a.Artist)
                         .OrderBy(a => a.Title) select a;

          
            if (genreID != null && genreID != 0)
            {
               albums = albums.Where(a => a.GenreID == genreID);
            }

            if (artistID != null && artistID != 0)
            {
                albums = albums.Where(a => a.ArtistID == artistID);
            } 
            
            if(id != null && id != "")
            {
                albums = albums.Where(a => a.Title.Contains(id));
            }

            var listAlbumsVM = new ListAlbumsViewModel
            {     
                
                Albums = albums.ToList(),
                Genres = new SelectList(_context.Genres.OrderBy(g => g.Name), "GenreID", "Name"),
                genreID = (genreID == null) ? 0 : (int)genreID,
                Artists = new SelectList(_context.Artists.OrderBy(a => a.Name), "ArtistID", "Name"),
                artistID = (artistID == null) ? 0 : (int)artistID
            };
            return View(listAlbumsVM);
        }
    
     

        // GET: Admin/Albums
        public async Task<IActionResult> Index()
        {
           
            var storeContext = _context.Albums.Include(a => a.Artist).Include(a => a.Genre);
            return View(await storeContext.ToListAsync());
        }

        // GET: Admin/Albums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums
                .Include(a => a.Artist)
                .Include(a => a.Genre)
                .SingleOrDefaultAsync(m => m.AlbumID == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Admin/Albums/Create
        public IActionResult Create()
        {
            ViewData["ArtistID"] = new SelectList(_context.Artists, "ArtistID", "Name");
            ViewData["GenreID"] = new SelectList(_context.Genres, "GenreID", "Name");
            return View();
        }

        // POST: Admin/Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlbumID,GenreID,ArtistID,Title,Price,AlbumArtUrl")] Album album)
        {
            if (ModelState.IsValid)
            {
                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistID"] = new SelectList(_context.Artists, "ArtistID", "Name", album.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Genres, "GenreID", "Name", album.GenreID);
            return View(album);
        }

        // GET: Admin/Albums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums.SingleOrDefaultAsync(m => m.AlbumID == id);
            if (album == null)
            {
                return NotFound();
            }
            ViewData["ArtistID"] = new SelectList(_context.Artists, "ArtistID", "Name", album.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Genres, "GenreID", "Name", album.GenreID);
            return View(album);
        }

        // POST: Admin/Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlbumID,GenreID,ArtistID,Title,Price,AlbumArtUrl")] Album album)
        {
            if (id != album.AlbumID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(album);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.AlbumID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistID"] = new SelectList(_context.Artists, "ArtistID", "Name", album.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Genres, "GenreID", "Name", album.GenreID);
            return View(album);
        }

        // GET: Admin/Albums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums
                .Include(a => a.Artist)
                .Include(a => a.Genre)
                .SingleOrDefaultAsync(m => m.AlbumID == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // POST: Admin/Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var album = await _context.Albums.SingleOrDefaultAsync(m => m.AlbumID == id);
            _context.Albums.Remove(album);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlbumExists(int id)
        {
            return _context.Albums.Any(e => e.AlbumID == id);
        }
    }
}

MusicStore/MusicStore/Areas/Admin/Views/Albums/Create.cshtml
@model MusicStore.Models.Album

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="table">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AlbumID" />
            <table>
                <tr>
                    <td> <label asp-for="AlbumArtUrl" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <input asp-for="AlbumArtUrl" class="form-control" />
                            <span asp-validation-for="AlbumArtUrl" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="ArtistID" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <select asp-for="ArtistID" class="form-control" asp-items="ViewBag.ArtistID"></select>
                            <span asp-validation-for="ArtistID" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="GenreID" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <select asp-for="GenreID" class="form-control" asp-items="ViewBag.GenreID"></select>
                            <span asp-validation-for="GenreID" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="Price" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="Title" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <div>
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </td>
                </tr>

            </table>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicStore/MusicStore/Areas/Admin/Views/Albums/Delete.cshtml
@model MusicStore.Models.Album

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AlbumArtUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artist.ArtistID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.GenreID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AlbumID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MusicStore/MusicStore/Areas/Admin/Views/Albums/Details.cshtml
@model MusicStore.Models.Album

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AlbumArtUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artist.ArtistID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.GenreID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AlbumID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MusicStore/MusicStore/Areas/Admin/Views/Albums/Edit.cshtml
@model MusicStore.Models.Album

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="table">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AlbumID" />
            <table>
                <tr>
                    <td> <label asp-for="AlbumArtUrl" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <input asp-for="AlbumArtUrl" class="form-control" />
                            <span asp-validation-for="AlbumArtUrl" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="ArtistID" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <select asp-for="ArtistID" class="form-control" asp-items="ViewBag.ArtistID"></select>
                            <span asp-validation-for="ArtistID" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="GenreID" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <select asp-for="GenreID" class="form-control" asp-items="ViewBag.GenreID"></select>
                            <span asp-validation-for="GenreID" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="Price" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label asp-for="Title" class="control-label"></label></td>
                    <td>
                        <div class="form-group">
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </td>
                </tr>

            </table>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicStore/MusicStore/Areas/Admin/Views/Albums/ListArtists.cshtml
@*@model MusicStore.Models.ViewModels.ListAlbumsViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-area="Admin" asp-controller="Album" asp-action="ListGenres" method="get">
    <label>Genre:</label>
    <select asp-for="genreID" asp-items="Model.Genres">
        <option value="0">-- Select a Genre ---</option>
    </select>
    <input type="submit" value="Filter" />
</form>

<form asp-area="Admin" asp-controller="Album" asp-action="ListArtist" method="get">
    <label>Artist:</label>
    <select id="artitstID" asp-for="artistID" asp-items="Model.Artists">
        <option value="0">-- Select an Artist ---</option>
    </select>
    <input type="submit" value="Filter" />
</form>
<form asp-area="Admin" asp-controller="Album" asp-action="ListTitles(title)" method="get">
    <label>Title:</label>
    <input type="text" id="artitstID" asp-for="artistID">
    <input type="submit" value="Filter" />
</form>



<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @(Html.DisplayNameFor(model => model.Albums[0].Artist))
            </th>

            <th>
                @(Html.DisplayNameFor(model => model.Albums[0].Genre))
            </th>
            <th>
                @(Html.DisplayNameFor(model => model.Albums[0].Title))
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Albums)
        {
            <tr>
                <td>
                    @(Html.DisplayFor(modelItem => item.Artist.Name))
                </td>
                <td>
                    @(Html.DisplayFor(modelItem => item.Genre.Name))
                </td>
                <td>
                    @(Html.DisplayFor(modelItem => item.Title))
                </td>


                <td>
                    <a asp-action="Edit" asp-route-id="@item.AlbumID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.AlbumID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.AlbumID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>*@

MusicStore/MusicStore/Areas/Admin/Views/Albums/ListGenres.cshtml
@model MusicStore.Models.ViewModels.ListAlbumsViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>



@using (Html.BeginForm("ListGenres", "Albums", FormMethod.Get))
{
    <select asp-for="genreID" asp-items="Model.Genres">
        <option value="0">-- Select a Genre ---</option>
    </select>
    <input type="submit" value="Filter" />
    <br />

    <select asp-for="artistID" asp-items="Model.Artists">
        <option value="0">-- Select a Artist ---</option>
    </select>
    <input type="submit" value="Filter" />

    <br />    <input type="text" asp-for="id">
    <input type="submit" value="Filter" /> 
}



<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @(Html.DisplayNameFor(model => model.Albums[0].Artist))
            </th>

            <th>
                @(Html.DisplayNameFor(model => model.Albums[0].Genre))
            </th>
            <th>
                @(Html.DisplayNameFor(model => model.Albums[0].Title))
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Albums)
        {
            <tr>
                <td>
                    @(Html.DisplayFor(modelItem => item.Artist.Name))
                </td>
                <td>
                    @(Html.DisplayFor(modelItem => item.Genre.Name))
                </td>
                <td>
                    @(Html.DisplayFor(modelItem => item.Title))
                </td>


                <td>
                    <a asp-action="Edit" asp-route-id="@item.AlbumID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.AlbumID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.AlbumID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>