MusicStore/MusicStore/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicStore.Models
{
    public class Artist
    {
        public int ArtistID { get; set; }
        public string Name { get; set; }

        public ICollection<Album> Albums { get; set; }
    }
}

MusicStore/MusicStore/Areas/Admin/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicStore.Data;
using MusicStore.Models;

namespace MusicStore.Areas.Admin
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]

    public class ArtistsController : Controller
    {
        private readonly StoreContext _context;

        public ArtistsController(StoreContext context)
        {
            _context = context;
        }

        public IActionResult FilterArtist(string id)
        {
            var artists = _context.Artists.Where(a => a.Name.StartsWith(id)).OrderBy(a => a.Name).ToList();
            return View( artists);
        }


        // GET: Admin/Artists
        public async Task<IActionResult> Index()
        {

            return View(await _context.Artists.ToListAsync());
        }

        // GET: Admin/Artists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .SingleOrDefaultAsync(m => m.ArtistID == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Admin/Artists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Artists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ArtistID,Name")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(artist);
        }

        // GET: Admin/Artists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.SingleOrDefaultAsync(m => m.ArtistID == id);
            if (artist == null)
            {
                return NotFound();
            }
            return View(artist);
        }

        // POST: Admin/Artists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArtistID,Name")] Artist artist)
        {
            if (id != artist.ArtistID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(artist.ArtistID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(artist);
        }

        // GET: Admin/Artists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .SingleOrDefaultAsync(m => m.ArtistID == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Admin/Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artists.SingleOrDefaultAsync(m => m.ArtistID == id);
            _context.Artists.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artists.Any(e => e.ArtistID == id);
        }
    }
}

MusicStore/MusicStore/Areas/Admin/Views/Artists/Create.cshtml
@model MusicStore.Models.Artist

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MusicStore/MusicStore/Areas/Admin/Views/Artists/Delete.cshtml
@model MusicStore.Models.Artist

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ArtistID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MusicStore/MusicStore/Areas/Admin/Views/Artists/Details.cshtml
@model MusicStore.Models.Artist

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ArtistID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MusicStore/MusicStore/Areas/Admin/Views/Artists/Edit.cshtml
@model MusicStore.Models.Artist

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ArtistID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MusicStore/MusicStore/Areas/Admin/Views/Artists/FilterArtist.cshtml
@model IEnumerable<MusicStore.Models.Artist>

@{
    ViewData["Title"] = "FilterArtist";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
@for (char c = 'A'; c <= 'Z'; c++)
{
    <a asp-area="Admin" asp-controller="Artists" asp-action="FilterArtist" asp-route-id="@c">@c</a>
}
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ArtistID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ArtistID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ArtistID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

MusicStore/MusicStore/Areas/Admin/Views/Artists/Index.cshtml
@model IEnumerable<MusicStore.Models.Artist>

@{
    ViewData["Title"] = "FilterArtist";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
@for (char c = 'A'; c <= 'Z'; c++)
{
    <a asp-area="Admin" asp-controller="Artists" asp-action="FilterArtist" asp-route-id="@c">@c</a>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ArtistID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ArtistID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ArtistID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>